services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apassword
    ports:
      - "55432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - jenkins-net

  papaja:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apassword
    networks:
      - jenkins-net

  jenkins:
    user: root
    build:
      context: ./jenkins-custom
    image: jenkins-gmail
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - jenkins-net

volumes:
  db-data:
  jenkins_home:
  sonarqube_data:
  sonarqube_logs:

networks:
  jenkins-net:
