version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apassword
    ports:
      - "55432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  papaja:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8088:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apassword

volumes:
  db-data:
